name: GitHub Streak
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  streak:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-streak-stats-image-generator@v1
        with:
          user_id: 189324171
          output: streak.svg
      - uses: actions/upload-artifact@v4
        with:
          name: streak
          path: streak.svg
